FROM maven:3.8.7-openjdk-18-slim as build
WORKDIR /app
COPY . .
RUN mvn clean package

FROM openjdk:19-jdk-alpine3.16
ARG branch=dev
LABEL BranchName=${branch}
RUN apk update && apk add /bin/sh && mkdir -p /opt/app
ENV PROJECT_HOME /opt/app
COPY --from=build /app/target/spring-boot-mongo-1.0.jar $PROJECT_HOME/spring-boot-mongo-1.0.jar
WORKDIR $PROJECT_HOME
CMD [ "java", "-jar", "./spring-boot-mongo-1.0.jar"]
